### ISSUE TITLE
Extension not working with x64 agent on vsts

### ISSUE THREAD

**Issue by AhmadHassanSahi** [qetza/replacetokens-task#13]
Facing this:
A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.

**Comment by qetza** [comment]
Hi @AhmadHassanSahi,
Thanks for reporting the issue. I don't think the issue is the operating system as i'm running tests on linux, macos and windows but i found that the minimum agent version was incorrectly set on the new version 6 of the task (fix incoming) due to an issue on some Microsoft documentation.

Could you provide me some more information on your environment:
- what version of the agent are you running on?
- what is the task version you are trying to?

**Comment by AhmadHassanSahi** [comment]
@qetza 

1. Agent Below
 ![Agent](https://github.com/qetza/replacetokens-task/assets/38754480/a5143bf8-d459-41b8-824b-a485f3f34b9b)

2. I am running Replace Token task 6

**Comment by qetza** [comment]
Hi @AhmadHassanSahi,
The issue is that the agent `2.181.2` doesn't support node16 execution handler which is the only one supported with the version 6 of the task.

I've already pushed a PR to fix the minimum agent version of the version 6 to `2.206.1`.

In your case i see 2 options:
1. upgrade your agent to at least version `2.206.1`
2. use version 5 of the task which has a minimum agent version of `2.144.0`

**Comment by AhmadHassanSahi** [comment]
@qetza  Thankyou for your quick response. I really appreciate it. I have tried with Task Version 5. its running successfully.
