### ISSUE TITLE
Paths are no longer normalised (V6)

### ISSUE THREAD

**Issue by MattJeanes** [qetza/replacetokens-task#16]
In the newest version 6 of the task, it seems that paths with multiple directory separators no longer resolve correctly that did on previous versions of the task.

Example: `D:\a\r1\a/_infrastructure.git/kubernetes/releases/ingress-nginx.yaml`

We can work around of course, but this is a bug compared to previous versions of the task :)

**Comment by qetza** [comment]
Hi @MattJeanes,
Is it just a log/output issue or your files are not read?
If it's on the logs, could you share the redacted logs to identify which one are not normalized?

**Comment by qetza** [comment]
Thanks @MattJeanes,
I'll take a look at the issue and try to find a fix in the `sources` input you must use only forward slashes whatever the platform, this is a constrains from the `fast-glob` library i'm using in v6 as the backslash is used as an escape character.

But I understand the issue that if you use variables with paths under windows they will have backslashes so maybe for windows only I'll do the replacement internally: replace all backslashes by forward slash so that its valid input for `fast-glob`.

**Comment by qetza** [comment]
Hi @MattJeanes,
Version 6.0.3 is released and fixes your issue 😄

**Comment by MattJeanes** [comment]
Amazing, just tried it now and seems to work!

It does seem to break if I explicitly enter a \ on Linux but that's fine we can and do normalise to Linux normally anyway so we'll just use forward slashes everywhere which is what we were doing anyway 🙂

Happy to close this unless you wanted to fix that little thing too, not sure what the behaviour of that was on older versions

**Comment by qetza** [comment]
On the previous version I was using a glob pattern library which didn’t support the backslash as an escape character I was normalizing the paths on all platforms.

With version 6 now the glob pattern syntax has more features needing the backslash as an escape character.

So I will say that in Linux if someone puts a backslash it’s to use as an escape character; I’m okay with this breaking change as normally you shouldn’t have backslash in paths on Linux. On windows, as you showed with your example, I cannot force users to put forward slashes so doing the normalization was mandatory.

**Comment by MattJeanes** [comment]
Makes sense, thanks for the explanation and thanks again for the quick fix! 🙂
