### ISSUE TITLE
sources input files in version 6.0.5

### ISSUE THREAD

**Issue by alexandreBeaulieu94** [qetza/replacetokens-task#29]
Hello,

I wanted to migrate from v5 -> v6 and I found that some sources files were missing in my new version with the same pattern.

In v5, if I use replace with targetFiles: "**/*.tfvars", all those files are found with the pattern:
![image](https://github.com/qetza/replacetokens-task/assets/49211050/a165fb53-2ca9-43b8-9fc5-b8f1d9e53fc7)

In v6, if I use sources: "**/*.tfvars", only those files are found:
![image](https://github.com/qetza/replacetokens-task/assets/49211050/7b2a0c09-a473-430d-9c69-6d4300facf03)

**Comment by qetza** [comment]
Hi @alexandreBeaulieu94,
That's an unintentional side effect of changing the library for glob pattern to `fast-glob`; by default `fast-glob` excludes files and directories starting with a dot (`.`) if not explicitly added to the pattern.

I'm going to fix this but in the meantime a workaround would be to explicitly include `.pipelines` in your sources:

```yaml
- task: replacetokens@6
  inputs:
    sources: '**/*.tfvars;.pipelines/**/*.tfvars'
```

**Comment by alexandreBeaulieu94** [comment]
@qetza thanks you for the answer😄

**Comment by mikefactorial** [comment]
I experienced a similar issue with case sensitivity in the sources that wasn't there previously when upgrading from v3 to v6.

I have several files in a directory that all start with either customDeploymentSettings or deploymentSettings. 

Previously the following would pick up all of them in v3
```
targetFiles: '**\*deploymentSettings*.json'
```

In v6 the following misses the customDeploymentSettings.json files presumably because it's case sensitive
```
sources: '**\*deploymentSettings*.json'
```

Easy enough to fix but others may run into it and I didn't see anything in the breaking changes about it. 

Thanks for the awesome tool and for continuing to maintain it! Obviously, the AzDO team just decided to punt on this capability since you've solved it so nicely 👍

**Comment by qetza** [comment]
Hi @mikefactorial,
Thanks for reporting this unseen breaking change also introduced with the new glob library which by default is case-sensitive.

I will add to the next version a new input to enable/disable case sensitive sources with value disable by default to have the previous behavior but in the meantime you can change your sources to `**\*[dD]eploymentSettings*.json`.

**Comment by qetza** [comment]
Hi @alexandreBeaulieu94, @mikefactorial,
I released a new version of v6 task which fixes your issues:
- Path matching is now by default case insensitive as in previous versions; this can be disabled with the `caseInsensitivePaths` input.
- Path matching is now by default including directories and files starting with a dot (`.`); this can be disabled with the `includeDotPaths` input.
